# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import contract_pb2 as Contract__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in Contract_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserById = channel.unary_unary(
                '/sales.UserService/GetUserById',
                request_serializer=Contract__pb2.UserIdRequest.SerializeToString,
                response_deserializer=Contract__pb2.UserMsg.FromString,
                _registered_method=True)
        self.GetAllUsers = channel.unary_unary(
                '/sales.UserService/GetAllUsers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Contract__pb2.GetAllUsersResponse.FromString,
                _registered_method=True)
        self.SetOnlineStatus = channel.unary_unary(
                '/sales.UserService/SetOnlineStatus',
                request_serializer=Contract__pb2.OnlineStatusRequest.SerializeToString,
                response_deserializer=Contract__pb2.OnlineStatusResponse.FromString,
                _registered_method=True)
        self.SetLastSeen = channel.unary_unary(
                '/sales.UserService/SetLastSeen',
                request_serializer=Contract__pb2.LastSeenRequest.SerializeToString,
                response_deserializer=Contract__pb2.LastSeenResponse.FromString,
                _registered_method=True)
        self.UpdateProfile = channel.unary_unary(
                '/sales.UserService/UpdateProfile',
                request_serializer=Contract__pb2.UpdateProfileRequest.SerializeToString,
                response_deserializer=Contract__pb2.UpdateProfileResponse.FromString,
                _registered_method=True)
        self.UpdateProfileImage = channel.unary_unary(
                '/sales.UserService/UpdateProfileImage',
                request_serializer=Contract__pb2.UpdateProfileImageRequest.SerializeToString,
                response_deserializer=Contract__pb2.UpdateProfileImageResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUserById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetOnlineStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLastSeen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProfileImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserById,
                    request_deserializer=Contract__pb2.UserIdRequest.FromString,
                    response_serializer=Contract__pb2.UserMsg.SerializeToString,
            ),
            'GetAllUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllUsers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Contract__pb2.GetAllUsersResponse.SerializeToString,
            ),
            'SetOnlineStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SetOnlineStatus,
                    request_deserializer=Contract__pb2.OnlineStatusRequest.FromString,
                    response_serializer=Contract__pb2.OnlineStatusResponse.SerializeToString,
            ),
            'SetLastSeen': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLastSeen,
                    request_deserializer=Contract__pb2.LastSeenRequest.FromString,
                    response_serializer=Contract__pb2.LastSeenResponse.SerializeToString,
            ),
            'UpdateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProfile,
                    request_deserializer=Contract__pb2.UpdateProfileRequest.FromString,
                    response_serializer=Contract__pb2.UpdateProfileResponse.SerializeToString,
            ),
            'UpdateProfileImage': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProfileImage,
                    request_deserializer=Contract__pb2.UpdateProfileImageRequest.FromString,
                    response_serializer=Contract__pb2.UpdateProfileImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sales.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sales.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sales.UserService/GetUserById',
            Contract__pb2.UserIdRequest.SerializeToString,
            Contract__pb2.UserMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sales.UserService/GetAllUsers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Contract__pb2.GetAllUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetOnlineStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sales.UserService/SetOnlineStatus',
            Contract__pb2.OnlineStatusRequest.SerializeToString,
            Contract__pb2.OnlineStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLastSeen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sales.UserService/SetLastSeen',
            Contract__pb2.LastSeenRequest.SerializeToString,
            Contract__pb2.LastSeenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sales.UserService/UpdateProfile',
            Contract__pb2.UpdateProfileRequest.SerializeToString,
            Contract__pb2.UpdateProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProfileImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sales.UserService/UpdateProfileImage',
            Contract__pb2.UpdateProfileImageRequest.SerializeToString,
            Contract__pb2.UpdateProfileImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateChatRoom = channel.unary_unary(
                '/sales.ChatService/CreateChatRoom',
                request_serializer=Contract__pb2.ChatRoomRequest.SerializeToString,
                response_deserializer=Contract__pb2.ChatRoomResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/sales.ChatService/SendMessage',
                request_serializer=Contract__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=Contract__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.GetMessages = channel.unary_unary(
                '/sales.ChatService/GetMessages',
                request_serializer=Contract__pb2.GetMessagesRequest.SerializeToString,
                response_deserializer=Contract__pb2.GetMessagesResponse.FromString,
                _registered_method=True)
        self.MarkAsRead = channel.unary_unary(
                '/sales.ChatService/MarkAsRead',
                request_serializer=Contract__pb2.MarkAsReadRequest.SerializeToString,
                response_deserializer=Contract__pb2.MarkAsReadResponse.FromString,
                _registered_method=True)
        self.CreateGroup = channel.unary_unary(
                '/sales.ChatService/CreateGroup',
                request_serializer=Contract__pb2.CreateGroupRequest.SerializeToString,
                response_deserializer=Contract__pb2.CreateGroupResponse.FromString,
                _registered_method=True)
        self.SendGroupMessage = channel.unary_unary(
                '/sales.ChatService/SendGroupMessage',
                request_serializer=Contract__pb2.SendGroupMessageRequest.SerializeToString,
                response_deserializer=Contract__pb2.SendGroupMessageResponse.FromString,
                _registered_method=True)
        self.AddGroupMember = channel.unary_unary(
                '/sales.ChatService/AddGroupMember',
                request_serializer=Contract__pb2.AddGroupMemberRequest.SerializeToString,
                response_deserializer=Contract__pb2.AddGroupMemberResponse.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateChatRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkAsRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendGroupMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddGroupMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateChatRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChatRoom,
                    request_deserializer=Contract__pb2.ChatRoomRequest.FromString,
                    response_serializer=Contract__pb2.ChatRoomResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=Contract__pb2.SendMessageRequest.FromString,
                    response_serializer=Contract__pb2.SendMessageResponse.SerializeToString,
            ),
            'GetMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessages,
                    request_deserializer=Contract__pb2.GetMessagesRequest.FromString,
                    response_serializer=Contract__pb2.GetMessagesResponse.SerializeToString,
            ),
            'MarkAsRead': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkAsRead,
                    request_deserializer=Contract__pb2.MarkAsReadRequest.FromString,
                    response_serializer=Contract__pb2.MarkAsReadResponse.SerializeToString,
            ),
            'CreateGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGroup,
                    request_deserializer=Contract__pb2.CreateGroupRequest.FromString,
                    response_serializer=Contract__pb2.CreateGroupResponse.SerializeToString,
            ),
            'SendGroupMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendGroupMessage,
                    request_deserializer=Contract__pb2.SendGroupMessageRequest.FromString,
                    response_serializer=Contract__pb2.SendGroupMessageResponse.SerializeToString,
            ),
            'AddGroupMember': grpc.unary_unary_rpc_method_handler(
                    servicer.AddGroupMember,
                    request_deserializer=Contract__pb2.AddGroupMemberRequest.FromString,
                    response_serializer=Contract__pb2.AddGroupMemberResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sales.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sales.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateChatRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sales.ChatService/CreateChatRoom',
            Contract__pb2.ChatRoomRequest.SerializeToString,
            Contract__pb2.ChatRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sales.ChatService/SendMessage',
            Contract__pb2.SendMessageRequest.SerializeToString,
            Contract__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sales.ChatService/GetMessages',
            Contract__pb2.GetMessagesRequest.SerializeToString,
            Contract__pb2.GetMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkAsRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sales.ChatService/MarkAsRead',
            Contract__pb2.MarkAsReadRequest.SerializeToString,
            Contract__pb2.MarkAsReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sales.ChatService/CreateGroup',
            Contract__pb2.CreateGroupRequest.SerializeToString,
            Contract__pb2.CreateGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendGroupMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sales.ChatService/SendGroupMessage',
            Contract__pb2.SendGroupMessageRequest.SerializeToString,
            Contract__pb2.SendGroupMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddGroupMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sales.ChatService/AddGroupMember',
            Contract__pb2.AddGroupMemberRequest.SerializeToString,
            Contract__pb2.AddGroupMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
